import { sql } from 'drizzle-orm'
import {
  boolean,
  index,
  integer,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core'
import { createdAt, pk, tstz, updatedAt } from './_columns'
import { users } from './users'

export const screenSharePolicy = pgEnum('screen_share_policy', ['everyone', 'hosts'])

/** Persistent (or ephemeral "instant meeting") rooms. The room key never reaches the server. */
export const rooms = pgTable(
  'rooms',
  {
    id: pk(),
    /** 10 random letters formatted `xxx-xxxx-xxx`; generated by the creating browser, unique. */
    slug: text().notNull(),
    name: text().notNull(),
    ownerId: uuid()
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    /** sha256(joinProof) where joinProof = HKDF(K, "blinq/v1/join|" + slug). Changes on key rotation. */
    joinProofHash: text().notNull(),
    keyVersion: integer().notNull().default(1),
    /** Optional room password (argon2id). */
    passwordHash: text(),
    /** Instant meetings are archived after the meeting ends. */
    ephemeral: boolean().notNull().default(false),
    waitingRoom: boolean().notNull().default(true),
    /** Live meeting lock; reset when the meeting ends. */
    locked: boolean().notNull().default(false),
    allowGuests: boolean().notNull().default(true),
    muteOnJoin: boolean().notNull().default(false),
    allowSelfUnmute: boolean().notNull().default(true),
    screenSharePolicy: screenSharePolicy().notNull().default('everyone'),
    chatEnabled: boolean().notNull().default(true),
    maxParticipants: integer().notNull().default(25),
    lastActiveAt: tstz(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    deletedAt: tstz(),
  },
  (t) => [uniqueIndex('rooms_slug_unique').on(t.slug), index('rooms_owner_idx').on(t.ownerId)],
)

export const roomMemberRole = pgEnum('room_member_role', ['cohost'])

/** Persisted co-hosts (registered users). Guest co-hosts are live-only (call_participants.room_role). */
export const roomMembers = pgTable(
  'room_members',
  {
    roomId: uuid()
      .notNull()
      .references(() => rooms.id, { onDelete: 'cascade' }),
    userId: uuid()
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    role: roomMemberRole().notNull().default('cohost'),
    createdAt: createdAt(),
  },
  (t) => [primaryKey({ columns: [t.roomId, t.userId] }), index('room_members_user_idx').on(t.userId)],
)

/**
 * Room invite links. The token is `base64url(idBytes ‖ HMAC(k_invite, idBytes)[0..16])`: derived, never stored,
 * re-derivable for the owner. Revocation, expiry and max uses live here.
 */
export const roomInvites = pgTable(
  'room_invites',
  {
    id: pk(),
    roomId: uuid()
      .notNull()
      .references(() => rooms.id, { onDelete: 'cascade' }),
    label: text(),
    createdBy: uuid().references(() => users.id, { onDelete: 'set null' }),
    /** null = never expires. */
    expiresAt: tstz(),
    /** null = unlimited. Enforced atomically (`UPDATE … WHERE use_count < max_uses RETURNING`). */
    maxUses: integer(),
    useCount: integer().notNull().default(0),
    revokedAt: tstz(),
    createdAt: createdAt(),
  },
  (t) => [index('room_invites_room_idx').on(t.roomId), index('room_invites_created_by_idx').on(t.createdBy)],
)

/** Guests (no account). `id` is sha256(token); the token lives in the per-room cookie `__Host-blinq_g_<slug>`. */
export const guestSessions = pgTable(
  'guest_sessions',
  {
    id: text().primaryKey(),
    roomId: uuid()
      .notNull()
      .references(() => rooms.id, { onDelete: 'cascade' }),
    displayName: text().notNull(),
    createdAt: createdAt(),
    expiresAt: tstz().notNull(),
    ip: text(),
  },
  (t) => [index('guest_sessions_room_idx').on(t.roomId), index('guest_sessions_expires_idx').on(t.expiresAt)],
)

/** One live meeting per room (partial unique index). A fresh random epoch per meeting derives fresh E2EE keys. */
export const meetings = pgTable(
  'meetings',
  {
    id: pk(),
    roomId: uuid()
      .notNull()
      .references(() => rooms.id, { onDelete: 'cascade' }),
    /** base64url of 16 random bytes; salt for per-meeting media/chat key derivation. */
    epoch: text().notNull(),
    livekitSid: text(),
    startedAt: tstz().notNull().defaultNow(),
    endedAt: tstz(),
    peakParticipants: integer().notNull().default(0),
  },
  (t) => [
    index('meetings_room_idx').on(t.roomId),
    uniqueIndex('meetings_one_live_per_room')
      .on(t.roomId)
      .where(sql`${t.endedAt} is null`),
  ],
)

export const participantRole = pgEnum('participant_role', ['host', 'cohost', 'participant'])
export const participantStatus = pgEnum('participant_status', [
  'waiting',
  'admitted',
  'joined',
  'left',
  'denied',
  'removed',
])

/**
 * Lobby, roster and bans in one table. `denied` and `removed` are final for their meeting.
 * `lkIdentity` is the LiveKit identity (`p_` + 16 random base62) and is unrelated to user ids.
 */
export const callParticipants = pgTable(
  'call_participants',
  {
    id: pk(),
    lkIdentity: text().notNull(),
    roomId: uuid()
      .notNull()
      .references(() => rooms.id, { onDelete: 'cascade' }),
    /** null while waiting before any meeting exists; attached when the meeting starts. */
    meetingId: uuid().references(() => meetings.id, { onDelete: 'cascade' }),
    userId: uuid().references(() => users.id, { onDelete: 'set null' }),
    guestSessionId: text().references(() => guestSessions.id, { onDelete: 'set null' }),
    /** Random per browser tab (sessionStorage); refresh-safe resume only with same session + clientId + meeting. */
    clientId: text().notNull(),
    displayName: text().notNull(),
    roomRole: participantRole().notNull().default('participant'),
    status: participantStatus().notNull(),
    micAllowed: boolean().notNull().default(true),
    cameraAllowed: boolean().notNull().default(true),
    /** Host-set volume for everyone (0–100), mirrored to the LiveKit `vol` attribute. */
    volumeLevel: integer().notNull().default(100),
    handRaisedAt: tstz(),
    requestedAt: tstz().notNull().defaultNow(),
    admittedAt: tstz(),
    admittedByParticipantId: uuid(),
    joinedAt: tstz(),
    leftAt: tstz(),
    ip: text(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    uniqueIndex('call_participants_identity_unique').on(t.lkIdentity),
    index('call_participants_room_status_idx').on(t.roomId, t.status),
    index('call_participants_meeting_idx').on(t.meetingId),
    index('call_participants_user_idx').on(t.userId),
    index('call_participants_guest_idx').on(t.guestSessionId),
    // The stale-waiting sweep runs every minute over the few waiting rows only.
    index('call_participants_waiting_idx')
      .on(t.requestedAt)
      .where(sql`${t.status} = 'waiting'`),
  ],
)
