/**
 * Room key handling and HKDF-SHA256 derivations. Spec: docs/SECURITY.md §3 and docs/API.md (crypto section).
 *
 * The room key K (32 random bytes) never leaves the browser. The only derivative that reaches the server is the
 * join proof, and the server stores only sha256(proof).
 */
import { fromBase64Url, randomBytes, toBase64Url, utf8 } from './encoding'

export const ROOM_KEY_BYTES = 32
export const EPOCH_BYTES = 16

const SLUG_ALPHABET = 'abcdefghjkmnpqrstuvwxyz' // no i, l, o
const SLUG_LENGTH = 10
const SLUG_PATTERN = /^[a-hj-kmnp-z]{3}-[a-hj-kmnp-z]{4}-[a-hj-kmnp-z]{3}$/
const CROCKFORD = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'

export const INFO = {
  join: 'blinq/v1/join|',
  media: 'blinq/v1/media|',
  chat: 'blinq/v1/chat|',
  safety: 'blinq/v1/safety|',
} as const

export type RoomKey = Uint8Array<ArrayBuffer>

export function generateRoomKey(): RoomKey {
  return randomBytes(ROOM_KEY_BYTES)
}

export function encodeRoomKey(key: RoomKey): string {
  return toBase64Url(key)
}

/** Parses the `k` fragment value. Throws on anything that is not exactly 32 bytes of base64url. */
export function decodeRoomKey(encoded: string): RoomKey {
  const key = fromBase64Url(encoded)
  if (key.length !== ROOM_KEY_BYTES) throw new TypeError('Room key must be 32 bytes')
  return key
}

/** Random slug `xxx-xxxx-xxx` from a 23-letter alphabet (~45 bits), generated by the creating browser. */
export function generateSlug(): string {
  const letters: string[] = []
  const limit = 256 - (256 % SLUG_ALPHABET.length) // rejection sampling keeps the distribution uniform
  while (letters.length < SLUG_LENGTH) {
    for (const byte of randomBytes(16)) {
      if (byte < limit && letters.length < SLUG_LENGTH) letters.push(SLUG_ALPHABET[byte % SLUG_ALPHABET.length]!)
    }
  }
  const s = letters.join('')
  return `${s.slice(0, 3)}-${s.slice(3, 7)}-${s.slice(7)}`
}

export function isValidSlug(slug: string): boolean {
  return SLUG_PATTERN.test(slug)
}

async function hkdf(ikm: Uint8Array<ArrayBuffer>, salt: Uint8Array<ArrayBuffer>, info: string, bytes: number) {
  const base = await crypto.subtle.importKey('raw', ikm, 'HKDF', false, ['deriveBits'])
  const bits = await crypto.subtle.deriveBits({ name: 'HKDF', hash: 'SHA-256', salt, info: utf8(info) }, base, bytes * 8)
  return new Uint8Array(bits)
}

/** Proves possession of K without revealing it: base64url(HKDF(K, salt = empty, "blinq/v1/join|" + slug)). */
export async function deriveJoinProof(key: RoomKey, slug: string): Promise<string> {
  return toBase64Url(await hkdf(key, new Uint8Array(0), INFO.join + slug, 32))
}

export interface MeetingKeys {
  /** Raw 32-byte key for LiveKit's ExternalE2EEKeyProvider({ keySize: 256 }).setKey(...). */
  mediaKey: ArrayBuffer
  /** AES-256-GCM key for the app-message envelope (chat, reactions). Non-extractable. */
  chatKey: CryptoKey
  /** 16 Crockford base32 characters in 4 groups (80 bits); proves only "we hold the same key". */
  safetyCode: string
}

/** Per-meeting keys. The epoch (16 random bytes from the server, base64url) makes every meeting use fresh keys. */
export async function deriveMeetingKeys(key: RoomKey, epoch: string, slug: string): Promise<MeetingKeys> {
  const salt = fromBase64Url(epoch)
  if (salt.length !== EPOCH_BYTES) throw new TypeError('Meeting epoch must be 16 bytes')
  const [media, chat, safety] = await Promise.all([
    hkdf(key, salt, INFO.media + slug, 32),
    hkdf(key, salt, INFO.chat + slug, 32),
    hkdf(key, salt, INFO.safety + slug, 10),
  ])
  const chatKey = await crypto.subtle.importKey('raw', chat, { name: 'AES-GCM', length: 256 }, false, [
    'encrypt',
    'decrypt',
  ])
  return { mediaKey: media.buffer, chatKey, safetyCode: formatSafetyCode(safety) }
}

/** 80 bits → 16 Crockford base32 characters → "ABCD-EFGH-JKMN-PQRS". */
export function formatSafetyCode(bytes: Uint8Array): string {
  if (bytes.length !== 10) throw new TypeError('Safety code needs 10 bytes')
  let bits = 0
  let value = 0
  let out = ''
  for (const byte of bytes) {
    value = (value << 8) | byte
    bits += 8
    while (bits >= 5) {
      out += CROCKFORD[(value >>> (bits - 5)) & 31]
      bits -= 5
    }
  }
  return out.match(/.{4}/g)!.join('-')
}
